In [134]:
import numpy as np

In [135]:
arr = np.arange(2, 20)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [136]:
arr[6]

np.int64(8)

In [137]:
arr[0:6]

array([2, 3, 4, 5, 6, 7])

In [138]:
arr[::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [139]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2])

In [140]:
sliced_arr = arr[0:5]
sliced_arr

array([2, 3, 4, 5, 6])

In [141]:
sliced_arr[:] = 30
sliced_arr

array([30, 30, 30, 30, 30])

In [142]:
arr

array([30, 30, 30, 30, 30,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [144]:
sliced_arr[2] = 133
arr

array([ 30,  30, 133,  30,  30,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19])

In [151]:
arr_2d = np.random.randint(2, 100, (5, 5))
arr_2d

array([[49, 24, 63, 89, 38],
       [45, 87, 92, 36, 66],
       [48, 79,  4,  2,  6],
       [91, 15, 28, 10, 80],
       [16, 91, 43, 78, 52]])

In [152]:
arr_2d[0, 4]

np.int64(38)

In [156]:
arr_2d[:3, 1:]

array([[24, 63, 89, 38],
       [87, 92, 36, 66],
       [79,  4,  2,  6]])

In [157]:
arr = np.arange(2, 10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False,  True,  True,  True,  True])

In [159]:
arr[bool_arr]

array([6, 7, 8, 9])

In [160]:
arr[arr%2==0]

array([2, 4, 6, 8])