In [71]:
import numpy as np

In [72]:
my_list = [25, 65, 98]
type(my_list)

list

In [73]:
np.array(my_list)

array([25, 65, 98])

In [74]:
my_arr = np.array(my_list)

In [75]:
type(my_arr)

numpy.ndarray

In [76]:
my_matrix = [[21, 32, 56], [12, 87, 10], [-2, 25, -356]]

In [77]:
np.array(my_matrix)

array([[  21,   32,   56],
       [  12,   87,   10],
       [  -2,   25, -356]])

In [78]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(1, 250, 20)

array([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241])

In [80]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [81]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [86]:
np.random.rand(20)

array([0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685734,
       0.72900717, 0.77127035, 0.07404465, 0.35846573, 0.11586906,
       0.86310343, 0.62329813, 0.33089802, 0.06355835, 0.31098232,
       0.32518332, 0.72960618, 0.63755747, 0.88721274, 0.47221493])

In [87]:
np.random.rand(2, 2)

array([[0.11959425, 0.71324479],
       [0.76078505, 0.5612772 ]])

In [88]:
# normal distribution
np.random.randn(2, 2)

array([[-0.03582604,  1.56464366],
       [-2.6197451 ,  0.8219025 ]])

In [89]:
np.random.randint(5, 150, 100)

array([ 46, 128,  67, 100,  56, 100, 136, 147,  33,  40,  17,  75,  90,
        32,  70,  49,  66, 138,  32,  32, 112,  48,  88,  34,  79, 132,
        96, 133, 125,  31, 125, 120,   7, 107, 141,  66,  55,  63, 122,
       100, 117,  66,  56,  16,  43, 134, 135, 117, 105, 117,  85, 117,
         6, 134,  58,  91, 133, 130, 134,  57,  72, 127, 149,  42,  28,
        73, 120, 102, 143, 148, 101, 128,  74,  97,   7,  94, 100,  56,
       132,  43,  86, 108, 133,  15,  46, 103,  11, 148,  94, 116,  64,
       117,   6, 133,  52, 144,  41,  13, 103,  52])

In [90]:
np.random.randint(5, 150, (5, 5))

array([[135,  58, 124, 120,  79],
       [117, 108,  88, 116, 103],
       [ 97, 132, 114,  86,  58],
       [ 72,  37, 146,  25,  52],
       [132, 140, 139, 149, 132]])

In [101]:
np.random.seed(42)
np.random.randint(4, 150, 10)

array([106,  96,  18, 110,  75,  24, 106, 125,  78,  91])

In [92]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr = arr.reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
rand_arr = np.random.randint(0, 1000, 20)
rand_arr

array([387, 600, 315,  13, 241, 776, 345, 564, 897, 339,  91, 366, 955,
       454, 427, 508, 775, 942,  34, 205])

In [106]:
rand_arr.max()

np.int64(955)

In [107]:
rand_arr.min()

np.int64(13)

In [108]:
rand_arr.argmax()

np.int64(12)

In [109]:
rand_arr.argmin()

np.int64(3)

In [110]:
rand_arr.dtype

dtype('int64')